correção bug docker-entrypoint, & funcionalidade retry webhook mercado pago

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -5,7 +5,13 @@ if [ -z "${LD_PRELOAD+x}" ] && [ -f /usr/lib/*/libjemalloc.so.2 ]; then
   export LD_PRELOAD="$(echo /usr/lib/*/libjemalloc.so.2)"
 fi
 
-# If running the rails server then create or migrate existing database
+if [ -z "$POSTGRES_USER" ] || [ -z "$POSTGRES_PASSWORD" ] || [ -z "$POSTGRES_DB" ]; then
+  echo "ERROR: Missing database credentials in environment variables."
+  exit 1
+fi
+
+export DATABASE_URL="postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres-db-service:5432/$POSTGRES_DB"
+
 if [ "${1}" == "./bin/rails" ] && [ "${2}" == "server" ]; then
   ./bin/rails db:prepare
 fi
